name: Validate Markdown File Extensions

on:
  pull_request:
    branches:
      - main
      - "[0-9]+"
      - "[0-9]+.[0-9]+"
    types: [opened, synchronize, reopened]

jobs:
  validate-mdx-extensions:
    # Skip backport PRs (titles starting with "Backport to branch" and branch names that contain the "MAJOR.MINOR-pull-PR_NUMBER" pattern)
    if: ${{ !(startsWith(github.event.pull_request.title, 'Backport to branch') && contains(github.head_ref, '-pull-')) }}
    uses: scalar-labs/actions/.github/workflows/validate-markdown-file-extensions-reusable.yml@main
    # Optional: customize the paths if they differ from defaults
    # with:
    #   docs-paths: "docs/en-us/,docs/ja-jp/"
    #   components-path: "src/components/"
