#!/usr/bin/env bash

set -e -o pipefail; [[ -n "$DEBUG" ]] && set -x

if [[ $# -ne 3 ]]; then
    echo "usage: $0 repo_owner repo_name pull_request_id"
    exit 1
fi

repo_owner=$1
repo_name=$2
pull_request_id=$3

# Get GitHub projects associated with the PR
gh pr view "$pull_request_id" --repo "$repo_owner/$repo_name" --json projectItems --jq '[.projectItems[].title] | join(",")'
